set(SRC_FILES
    AppConfig.cpp
    AppStart.cpp
    AppMenu.cpp
    AppLevelSelect.cpp
    AppPlayer.cpp
    AppCollision.cpp
    AppMovement.cpp
    AppCamera.cpp
    AppShooter.cpp
    AppBoss.cpp
    AppRotor.cpp
    AppUpdate.cpp
    AppEnd.cpp
    common/AssetPath.cpp
    game/BoxDrawable.cpp
    game/LevelData.cpp
    game/TmxLoader.cpp
    game/Collision.cpp
)

set(INCLUDE_FILES
    App.hpp
    common/AssetPath.hpp
    game/BoxDrawable.hpp
    game/LevelData.hpp
    game/TmxLoader.hpp
    game/Collision.hpp
)

set(TEST_FILES
)
